In [1]:
import time

In [2]:
start_notebook = time.time()

In [3]:
import warnings
warnings.filterwarnings("ignore")

# 1. Parameters

In [4]:
name_dataset = 'IMDB'
name_model = 'roberta-base'
seed = 3
part = 4

In [5]:
path_open = f'/content/drive/MyDrive/Finetuned-encoders-LLM-Prompting/03.Inference/{name_dataset}/post8/df_test_{part}.csv'

In [6]:
path_save = f'/content/drive/MyDrive/Finetuned-encoders-LLM-Prompting/03.Inference/{name_dataset}/post9/df_test_{part}.csv'

In [7]:
path_credentials = f'/content/drive/MyDrive/Finetuned-encoders-LLM-Prompting/credentials/cloudrun-invoker-only.json'

# 2. Load Environment

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
import json
import requests
import pandas as pd
import google.auth.transport.requests
from google.oauth2 import service_account

In [10]:
SERVICE_URL = f"https://{name_dataset.replace('_', '-').lower()}-{name_model}-seed-{seed}-272427236032.us-central1.run.app"

In [11]:
credentials = service_account.IDTokenCredentials.from_service_account_file(
    path_credentials,
    target_audience=SERVICE_URL)

auth_req = google.auth.transport.requests.Request()
credentials.refresh(auth_req)

In [12]:
def predict_label(text):

  payload = {"text": text}

  headers = {
      "Authorization": f"Bearer {credentials.token}",
      "Content-Type": "application/json"
  }

  start = time.perf_counter()

  resp = requests.post(f"{SERVICE_URL}/", headers=headers, json=payload, timeout=60)

  end = time.perf_counter()

  latency_ms = (end - start) * 1000

  output = {
      'label': int(json.loads(resp.text)['prediction']),
      'latency': latency_ms
  }

  return output

# 3. Load Dataset

In [13]:
df = pd.read_csv(path_open)

In [14]:
df.shape

(2500, 19)

In [15]:
pred_label = []
pred_latency = []

In [16]:
for i in range(len(df)):

  text = df['text'].iloc[i]
  output = predict_label(text)

  pred_label.append(output['label'])
  pred_latency.append(output['latency'])

  if (i % 10) == 0:
    print(i)

0

10

20

30

40

50

60

70

80

90

100

110

120

130

140

150

160

170

180

190

200

210

220

230

240

250

260

270

280

290

300

310

320

330

340

350

360

370

380

390

400

410

420

430

440

450

460

470

480

490

500

510

520

530

540

550

560

570

580

590

600

610

620

630

640

650

660

670

680

690

700

710

720

730

740

750

760

770

780

790

800

810

820

830

840

850

860

870

880

890

900

910

920

930

940

950

960

970

980

990

1000

1010

1020

1030

1040

1050

1060

1070

1080

1090

1100

1110

1120

1130

1140

1150

1160

1170

1180

1190

1200

1210

1220

1230

1240

1250

1260

1270

1280

1290

1300

1310

1320

1330

1340

1350

1360

1370

1380

1390

1400

1410

1420

1430

1440

1450

1460

1470

1480

1490

1500

1510

1520

1530

1540

1550

1560

1570

1580

1590

1600

1610

1620

1630

1640

1650

1660

1670

1680

1690

1700

1710

1720

1730

1740

1750

1760

1770

1780

1790

1800

1810

1820

1830

1840

1850

1860

1870

1880

1890

1900

1910

1920

1930

1940

1950

1960

1970

1980

1990

2000

2010

2020

2030

2040

2050

2060

2070

2080

2090

2100

2110

2120

2130

2140

2150

2160

2170

2180

2190

2200

2210

2220

2230

2240

2250

2260

2270

2280

2290

2300

2310

2320

2330

2340

2350

2360

2370

2380

2390

2400

2410

2420

2430

2440

2450

2460

2470

2480

2490

In [17]:
df[f'{name_model}-seed-{seed}-label'] = pred_label
df[f'{name_model}-seed-{seed}-latency'] = pred_latency

In [18]:
df[f'{name_model}-seed-{seed}-label'].value_counts()

roberta-base-seed-3-label
0    1252
1    1248
Name: count, dtype: int64

In [19]:
df[f'{name_model}-seed-{seed}-latency'].describe()

count    2500.000000
mean      704.294435
std       355.257879
min       213.197017
25%       444.863975
50%       583.734872
75%       902.832708
max      2359.652424
Name: roberta-base-seed-3-latency, dtype: float64

# 4. Save Dataset

In [20]:
df.to_csv(path_save, index = False)

# 5. Execution Time

In [21]:
end_notebook = time.time()

In [22]:
delta_notebook = end_notebook - start_notebook
hours_notebook, rem_notebook = divmod(delta_notebook, 3600)
minutes_notebook, seconds_notebook = divmod(rem_notebook, 60)

print(f"Execution Notebook: {int(hours_notebook)}h {int(minutes_notebook)}m {seconds_notebook:.2f}s")

Execution Notebook: 0h 31m 23.89s